// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlbdmwkuhrktlzvtgllq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsYmRtd2t1aHJrdGx6dnRnbGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDI1OTAsImV4cCI6MjA3MTcxODU5MH0.D36_pWJND-wRlPfR_l8Ec_ITpuA1b4gVh3vYv_c8g2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});